---
- name: influxdb repo
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL \$releasever
    file: influxdb
    baseurl: https://repos.influxdata.com/centos/\$releasever/\$basearch/stable
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes
    enabled: yes
    state: present

- name: telegraf install
  yum:
    name: telegraf
    state: present

- name: ipmitool install
  yum:
    name: ipmitool
    state: present

- name: udev rule to give telegraf ipmi access
  copy:
    src: 52-telegraf-ipmi.rules
    dest: /etc/udev/rules.d/52-telegraf-ipmi.rules
    owner: root
    group: root
    mode: 0664
  notify: apply udev

- name: telegraf config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: 0755
    backup: yes
  notify: restart telegraf

- name: telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes
